"""Add created_at to votes

Revision ID: b0ed920ea5d3
Revises: 3901bb7e087d
Create Date: 2025-08-12 15:43:32.115339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ed920ea5d3'
down_revision = '3901bb7e087d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'created_at')
    # ### end Alembic commands ###
